[package]
name = "subd-gh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.18", features = [ "macros", "rt" ] }
graphql_client = { version = "0.10.0", features = [ "reqwest" ] }
reqwest = "0.11.10"
serde = "1.0.137"
anyhow = "1.0.57"
